server:
  port: 8080
  servlet:
    contextPath: /api

spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch_phayao
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
      properties:
        path:
          home: target/elastic-embedded